//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveTango.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveTango.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *01*
        ///f,3,0,1
        ///t,3,0,4
        ///t,2,1,5
        ///t,2,2,2
        ///f,2,3,3
        ///t,3,3,0
        ///t,2,4,1
        ///f,3,4,3
        ///T
        ///*02*
        ///t,3,0,2
        ///f,3,0,3
        ///f,2,3,2
        ///t,2,3,4
        ///t,3,3,5
        ///t,2,4,1
        ///f,2,4,2
        ///f,3,5,2
        ///T
        ///*03*
        ///t,2,0,4
        ///t,3,0,5
        ///t,2,3,2
        ///t,3,2,3
        ///t,2,4,1
        ///f,2,3,4
        ///f,2,4,4
        ///f,3,5,2
        ///T
        ///*04*
        ///t,2,0,0
        ///t,3,0,2
        ///t,2,0,3
        ///f,2,0,4
        ///f,2,1,4
        ///t,2,3,0
        ///f,2,5,0
        ///f,3,3,1
        ///t,3,2,5
        ///T
        ///*05*
        ///t,2,0,0
        ///t,2,0,1
        ///f,3,0,2
        ///t,2,0,5
        ///t,3,1,2
        ///t,2,2,3
        ///t,2,1,4
        ///f,2,3,4
        ///f,2,4,1
        ///f,2,5,0
        ///f,2,5,2
        ///t,2,4,4
        ///T
        ///*06*
        ///t,2,0,1
        ///f,2,0,2
        ///t,2,0,4
        ///t,2,2,2
        ///t,3,1,3
        ///f,2,3,4
        ///f, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string levelsetup {
            get {
                return ResourceManager.GetString("levelsetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap main_backround {
            get {
                object obj = ResourceManager.GetObject("main_backround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
